name: .github/workflows/flutter-build.yml

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Configure Custom Server
        run: |
          sed -i 's/://rustdesk.com{{ secrets.DEFAULT_RENDEZVOUS_SERVER }}/g' libs/hbb_common/src/config.rs
          sed -i 's/0eVuKk5niH1Xp.../${{ secrets.DEFAULT_RS_PUB_KEY }}/g' libs/hbb_common/src/config.rs

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-custom-apk
          path: build/app/outputs/flutter-apk/app-release.apk
